# datasoure默认使用JDBC
spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
      
sk:
  auth:
    clientId: suke
    clientSecret: sk172839456
    scope: server


logging:
  config: classpath:logback.xml

